/** Known G League franchise names by BRef abbreviation (current + historical). */
export const GLEAGUE_TEAM_NAMES: Record<string, string> = {
  ABQ: "Albuquerque Thunderbirds",
  ACC: "Agua Caliente Clippers",
  ANA: "Anaheim Arsenal",
  ARK: "Arkansas RimRockers",
  ASH: "Asheville Altitude",
  AST: "Austin Toros",
  AUS: "Austin Spurs",
  BAK: "Bakersfield Jam",
  BIR: "Birmingham Squadron",
  CAN: "Canton Charge",
  CCG: "Capital City Go-Go",
  CLB: "Columbus Riverdragons",
  COL: "Colorado 14ers",
  CPS: "College Park Skyhawks",
  DAK: "Dakota Wizards",
  DEL: "Delaware Blue Coats",
  DLW: "Delaware 87ers",
  EBH: "Erie BayHawks",
  ERI: "Osceola Magic",
  FAY: "Fayetteville Patriots",
  FLO: "Florida Flame",
  FTW: "Fort Worth Flyers",
  FWN: "Noblesville Boom",
  GBO: "Greensboro Swarm",
  GLI: "G League Ignite",
  GRE: "Greenville Groove",
  GRG: "Grand Rapids Gold",
  GRR: "Grand Rapids Drive",
  HAW: "Erie BayHawks",
  HUN: "Huntsville Flight",
  IDA: "Idaho Stampede",
  IWA: "Iowa Wolves",
  LAK: "Lakeland Magic",
  LIN: "Long Island Nets",
  LOS: "South Bay Lakers",
  MAI: "Maine Celtics",
  MCC: "Motor City Cruise",
  MHU: "Memphis Hustle",
  MNE: "Maine Celtics",
  MOB: "Mobile Revelers",
  MXC: "Capitanes de Ciudad de México",
  NAS: "Northern Arizona Suns",
  NMX: "New Mexico Thunderbirds",
  OKL: "Oklahoma City Blue",
  ONT: "Ontario Clippers",
  RAP: "Raptors 905",
  REN: "Stockton Kings",
  RGV: "Rio Grande Valley Vipers",
  RIP: "Rip City Remix",
  ROA: "Roanoke Dazzle",
  SBL: "South Bay Lakers",
  SCW: "Santa Cruz Warriors",
  SDC: "San Diego Clippers",
  SLC: "Salt Lake City Stars",
  SPR: "Grand Rapids Gold",
  SXF: "Sioux Falls Skyforce",
  TEX: "Texas Legends",
  TUL: "Oklahoma City Blue",
  UTA: "Utah Flash",
  VAL: "Valley Suns",
  WCB: "Windy City Bulls",
  WES: "Westchester Knicks",
  WIS: "Wisconsin Herd",
};

export function getStaticTeamName(abbrev: string): string | null {
  return GLEAGUE_TEAM_NAMES[abbrev.toUpperCase()] ?? null;
}
